# Generated by Django 4.0.1 on 2022-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='India_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('total_cases', models.IntegerField()),
                ('total_deceased', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
            ],
        ),
    ]
